name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
        cache: 'npm'

    - name: Npm install
      run: |
        rm -rf node_modules package-lock.json
        npm install

    - name: Build
      run: npm run build
